### PR TITLE
Buffer method

### PR DESCRIPTION
**Pull request by aklatzke**
This is a proposed PR containing the following changes that mostly target the Node platform:

- Moved mocha up to v6.2.0 from v.5.2.0 (to address the auto-dependency PR)
- Added the ability to specify the SVG `viewBox` property
  - When rendering in NodeJS, some engines ignore the width/height of an SVG if they don't have the `viewBox` property
  - this is optional, if you don't call the `.viewBox` method, none will be specified
- Added ability to render to a buffer directly from the SVG library; this will allow users to pass either an `fs.readFile()` call or a result from `svg-builder()...buffer()` interchangeably 
- Added a .gitignore file, ignoring `node_modules` folder

### CODE REVIEW

**Comment by aklatzke** [comment]
It looks like builds are failing due to an NPM error for both my branch and the auto-generated branch, capture of the error output below:

Screen Shot 2019-07-26 at 5 04 22 PM

**Comment by JoeChapman** [comment]
Hi @aklatzke thank you for your contribution. Have you had an opportunity to find a solution to the build error?

**Comment by JoeChapman** [comment]
@aklatzke it looks like the issue is to do with the Node.js version.
This module was first built when ~0.11 was LTS, as such, files in this module use "use strict" pragma's and `const` and other more recent additions to es aren't supported. 

Screen Shot 2019-09-21 at 08 58 05

**Comment by JoeChapman** [comment]
@aklatzke It's a bit late, but I'm doing some work on this repo to update

**Pull request merged**
